services:
  dashboard:
    image: ghcr.io/elitealma/logistica:latest
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - pegasus_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.logistica.rule=Host(`logistica.pegasus360agency.com`)"
        - "traefik.http.routers.logistica.entrypoints=websecure"
        - "traefik.http.routers.logistica.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.logistica.loadbalancer.server.port=3000"

networks:
  pegasus_net:
    external: true
